# Generated by Django 4.2 on 2023-05-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50, verbose_name='Название меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, verbose_name='Название пункта меню')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('parent', models.CharField(max_length=30, verbose_name='Parent')),
                ('has_children', models.BooleanField(default=False, verbose_name='Имеет подменю')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tree_menu.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
